Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 140
  Exclude:
    - "spec/**/*"

# Offense count: 42
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - 'Rakefile'

Style/LineEndConcatenation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

# TODO: check again (force to %r literal)
Style/RegexpLiteral:
  Enabled: true

Style/StringLiterals:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/RedundantPercentQ:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    collect: "map"
    collect!: "map!"
    inject: "inject"
    detect: "find"
    find_all: "select"

Style/PerlBackrefs:
  Enabled: false
